### ISSUE TITLE
Future direction of rules_nixpkgs regarding nix flakes

### ISSUE THREAD

**Issue by benradf** [tweag/rules_nixpkgs#348]
**Is your feature request related to a problem? Please describe.**
With the Nix ecosystem moving towards [flakes](https://nixos.wiki/wiki/Flakes) we should start thinking about what this means for rules_nixpkgs. Flakes are still experimental in Nix and will need to stabilise before we can fully commit to an approach, but starting the discussion now and exploring ideas will help us prepare.

Some things to think about:
- How can flakes be integrated into rules_nixpkgs?
- How can they benefit users?
- What API improvements can they enable?
- etc

Discussions on the subject:
-  [Flakes and support for Nix evaluation cache](https://github.com/tweag/rules_nixpkgs/discussions/341)
- [Flakes first-class support](https://github.com/tweag/rules_nixpkgs/discussions/342)

**Comment by rickvanprim** [comment]
The current approach I'm attempting to use is having a Flake at the `WORKSPACE` level that defines both the `devShell` and a `bazel` set under `packages."${system}"` containing any derivations I want to pull into Bazel.  From there, I quickly wrote `nix_flake_package()` (using `nixpkgs_package()` as a starting point) that uses `nix build` to get the output path for a given derivation.
Example:
```bazel
nix_flake_package(
    name = "nix_rust",
    nix_flake_file = "//:flake.nix",
    nix_flake_lock_file = "//:flake.lock",
    package = "bazel.rust",
)
```
This expand to `nix build <nix_flake_file.dirname>#bazel.rust --print-out-paths --out-link bazel-support/nix-out-link <nixopts>` and then uses the same logic as `nixpkgs_package()`.  One of the main upsides I see is not needing the `repository`/`repositories` parameters of `nixpkgs_package()` as the Flake evaluation takes care of all of that and Bazel doesn't have to separately fetch them.

Rough docs:
```
Make the content of a local Nix Flake package available in the Bazel workspace.

Args:
  name: A unique name for this repository.
  nix_flake_file: Label to `flake.nix` that will be evaluated.
  nix_flake_lock_file: Label to `flake.lock` that corresponds to `nix_flake_file`.
  nix_flake_file_deps: Additional dependencies of `nix_flake_file` if any.
  package: Nix Flake package to make available.  The default package will be used if not specified.
  ... <build_file docs+behavior copied from `nixpkgs_package()`
```

If this approach/API seems reasonable, I'd be happy to put up a PR 🙂
